---
- name: installing and launching filebeat & metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.7.1-amd64.deb

  - name: install filebeat deb
    command: sudo dpkg -i filebeat-7.7.1-amd64.deb

  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/filebeat.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable and configure filebeat module
    command: sudo filebeat modules enable system
    command: sudo filebeat setup
    command: sudo service filebeat start
    command: sudo systemctl enable filebeat

  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.7.1-amd64.deb

  - name: install metricbeat deb
    command: sudo dpkg -i metricbeat-7.7.1-amd64.deb

  - name: drop in metricbeat.yml
    copy:
      src: /etc/ansible/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure metricbeat module
    command: sudo metricbeat modules enable docker
    command: sudo metricbeat setup
    command: sudo service metricbeat start
    command: sudo systemctl enable metricbeat


